### ISSUE TITLE
Server timings reported in seconds instead of milliseconds?

### ISSUE THREAD

**Issue by cannikin** [dpogue/rails_server_timings#1]
I'd love to open a PR, but I have no idea if this is actually a problem or if I have some weird Chrome setup? So I can see server timings added to the headers properly:

![image](https://cloud.githubusercontent.com/assets/300/24157061/8ed24d7c-0e15-11e7-8393-039d2f0c65e3.png)

But when I switch to the Timing tab to see the results, it looks like Chrome is interpreting the numbers as seconds:

![image](https://cloud.githubusercontent.com/assets/300/24157089/a0b903aa-0e15-11e7-879f-8b2a1980ce57.png)

The `db` line (reported as 32.9ms in the header) is transformed into 32.9 seconds in the report, same with `view` (230 seconds is 3.8 minutes). Maybe Chrome requires a unit after the time?

I'm running Chrome 56 and Rails 5.0.2.

**Comment by dpogue** [comment]
hmm, the spec doesn't actually specify units... but it seems like the browser is expecting seconds

**Comment by dpogue** [comment]
Just published v1.0.2 with a fix for this. Let me know if you're still seeing weird timings :)

**Comment by bmesuere** [comment]
I've got the opposite issue. The server returns a value in seconds, i.e. `Server-Timing:view=0.322, db=0.018, total=0.350`, but the browser interprets this as ms.
I'm running Chrome 59.0.3063.4 dev (64-bit) on my mac.

**Comment by dpogue** [comment]
Yeah, apparently the spec does say it's supposed to be milliseconds, and Chrome fixed their bug in version 58. I've got [a commit](https://github.com/dpogue/rails_server_timings/commit/b5040909a3e9a459ec8b310eb2282750d5d6cf85) on master that tests the Chrome version (ugh) and returns seconds or milliseconds. I'll make a new release later today.

**Comment by dpogue** [comment]
Released as 1.0.4 :)
