### ISSUE TITLE
Update header format

### ISSUE THREAD

**Issue by cvazac** [dpogue/rails_server_timings#8]
Please note that the response header format has evolved:
Old:
```
Server-Timing: <name>=<duration>; <description>
```

New:
```
Server-Timing: <name>; dur=<duration>; desc=<description>
```

Example:
```
Server-Timing: db; dur=123.4; desc="database access"
```

[Spec PR](https://github.com/w3c/server-timing/commit/1cf183e08407ada77da62e628422fea8ff45b64a)

[Updates in Chrome](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/network/HTTPParsersTest.cpp?q=parseservertiming&sq=package:chromium&l=528)

**Comment by dpogue** [comment]
Do you know which version of Chrome has this change? It looks like it was made in November, so my guess is that it's in Chrome 65 (current dev channel)?

**Comment by cvazac** [comment]
Yep, 65.
